schema-version = 1
release-version = "1.31.0"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[vendor.ethan]
registry = "750890591789.dkr.ecr.ap-northeast-1.amazonaws.com"

[sdk]
name = "bottlerocket-sdk"
version = "0.50.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "1.0.4"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "5.4.1"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-ethan"
version = "5.4.1"
vendor = "ethan"
